### ISSUE TITLE
[build] Dependabot supports Go, it should be added.

### ISSUE THREAD

**Issue by kaby76** [antlr/grammars-v4#3522]
This took me a while to figure out, but it's possible. And, extracting the Antlr tool version string from the go.mod file should be easy.

There are several tricks for this to happen.
* The dependabot.yml file needs to have an entry for Go.
```
  - package-ecosystem: "gomod"
    directory: "/templates/Go"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    labels:
      - "infrastructure"
      - "dependencies"
```
* The templates, and trgen, have to, again, be modified. The dependabot code requires any .go files to be parsible. That means that they cannot be templated. But, they have to in order to get the import paths correct in the source code. The trick is to make sure it does not have the .go suffix!! So, we need to replace the ".meta" hack. All templated files must have the .stg suffix and be StringTemplate group template files. (`templates/Go/test.go` => `templates/Go/test.go.stg`). `templates/Go/go.mod` is not templated, so it remains as is for Dependabot to modify.
* The file `templates/Go/build.sh` should have a grep/awk of go.mod to extract the string.
